# Generated by Django 2.2.6 on 2021-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210405_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку.', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
