# Generated by Django 2.2.6 on 2021-04-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210411_2109'),
        ('posts', '0010_profile'),
    ]

    operations = [
    ]
